# Generated by Django 4.2 on 2024-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
