# Generated by Django 4.2 on 2024-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tenantuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.'),
        ),
    ]
