# Generated by Django 4.2 on 2024-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_tenantuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='is_superuser',
            field=models.BooleanField(default=True, help_text='Designates whether the user is a super user.'),
        ),
    ]
